main: eu.endercentral.crazy_advancements.CrazyAdvancements
name: CrazyAdvancementsAPI
version: ${project.version}
api-version: 1.13
load: STARTUP
author: ZockerAxel
commands:
  cagrant:
    usage: /<command> <Player> <Manager>|file <Advancement> [Criteria...]
    description: Grants <Advancement>-[Criteria...] to <Player> in <Manager>
  carevoke:
    usage: /<command> <Player> <Manager Name>|file <Advancement> [Criteria...]
    description: Revokes <Advancement>-[Criteria...] from <Player> in <Manager>
  showtoast:
    usage: /<command> <Player> <Icon> <Message>
    description: Displays a Toast Advancement Message
